version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:1.9.2
       - image: circleci/ruby:2.4.1

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies

      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            bundle exec rake test

      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
